export default {
    en: {
      register: "Register",
      sign_in: "Sign in",
      sign_out: "Sign out",
      no_account_yet:"no account yet? register a new account",
      password:"Password",
      password_again:"Password again",
      password_rule: "Password length should between 6-20 and must contain both character and number",
      new_password:"new password",
      new_password_again:"new password again",
      forget_pass:"Forgot your password?",
      reset_pass:"Reset your password",
      welcome_signin:"Welcome to sign in page",
      welcome_register:"Welcome to register in page",
      sign_in_exist:"sign in to an existing account",
      input_captcha:"input captcha",
      change_captcha:"change captcha",
      send:"Send",
      send_vcode_to_email:"send vcode to my email",
      complete_vcode_to_email:"please complete email and captcha before send vcode",
    },
    zh: {
      register: "注册",
      sign_in: "登陆",
      sign_out: "退出",
      no_account_yet:"没有账户？点击注册",
      password:"密码",
      password_again:"再次输入密码",
      password_rule: "密码长度在6到20之前,并且包含英文字符和数字",
      new_password:"新密码",
      new_password_again:"再次确认新密码",
      forget_pass:"忘记密码?",
      reset_pass:"重置密码",
      welcome_signin:"欢迎来到登陆页面",
      welcome_register:"欢迎来到注册页面",
      sign_in_exist:"登陆现有账户",
      input_captcha:"输入验证码",
      change_captcha:"更换验证码",
      send:"发送",
      send_vcode_to_email:"发送vcode到我的邮箱",
      complete_vcode_to_email:"请填写email和验证码,然后再发送vcode",
    },
  };